### ISSUE TITLE
Copyedit

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/n-days-of-christmas#1]
Hi @LornaLynch and @lauraclay,

Could I get a copy edit on this please.

Cheers

**Comment by LornaLynch** [comment]
Sure: coming up

**Comment by LornaLynch** [comment]
@MarcScott I've finished the copy edit on everything apart from worksheet.org (worksheet.md is done): I'm not sure how the formatting is supposed to work on this. I tried copying and pasting some of my corrections from the worksheet.md, and this has caused some formatting errors. Do we need two copies of the worksheet, or is there a reason for the .org file of which I'm not aware? Thanks.

**Comment by LornaLynch** [comment]
Other than the above query, the worksheet doesn't have a "What next?". This may need to be added? 

Apart from that, you are good to go.

**Comment by MarcScott** [comment]
@LornaLynch  Awesome - the worksheet.org will be removed. I write my original in org-mode in Emacs and convert to markdown. I'll add the What next now. Cheers
