### ISSUE TITLE
Artwork

### ISSUE THREAD

**Issue by MarcScott** [raspberrypilearning/n-days-of-christmas#2]
Hi @samalderhyde 

Could I get some Christmas artwork for this one please. It's based on the 12 Days of Christmas song, but produces random output:

Sample output from the code:

On the 12th day of Christmas, my true love sent to me
12 Surgeons a stabbing
11 Politicians a precooling
10 Bumboat Mans a bilging
9 Buryemans a blotching
8 Artificers a alliterating
7 Software Engineers a safemaking
6 Gannekers a guttling
5 Gold rings
4 Calling birds
3 French hens
2 Turtle Doves
and a Partridge in a pair tree

**Comment by samalderhyde** [comment]
Hi Marc,

This is well funny!
I'll do my best before Christmas but I've got some urgent items in the queue at the moment

**Comment by LizUpton** [comment]
Sam, do you have any generic Chrismacular stuff that we can use as a placeholder?

(Even a Christmas tree or something would be fine.)

**Comment by samalderhyde** [comment]
Just having a rummage now - I'm pretty sure I do

**Comment by samalderhyde** [comment]
Bumboat Mans!
